### ISSUE TITLE
Delete stale Greenkeeper branches

### ISSUE THREAD

**Issue by Fdawgs** [fastify/env-schema#123]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Greenkeeper shutdown in 2020, so these can be removed.
Would make forking and working on this repo a bit quicker without the forks flooding the CLI when running `git branch`.

I've removed old Greenkeeper branches in repos where i have permissions, but do not have it for this.

**Comment by climba03003** [comment]
Removed.

**Comment by Fdawgs** [comment]
Thanks @climba03003

**Comment by Fdawgs** [comment]
@climba03003 Are you able to get https://github.com/fastify/light-my-request as well please?
Every other repo is ok.

**Comment by climba03003** [comment]
> @climba03003 Are you able to get https://github.com/fastify/light-my-request as well please? Every other repo is ok.

Yes, removed all stale branches.
