### ISSUE TITLE
Can i use with dotenv-flow?

### ISSUE THREAD

**Issue by gustawdaniel** [fastify/env-schema#13]
I propose to integrate with 

https://www.npmjs.com/package/dotenv-flow

instead of dotenv

**Comment by jsumners** [comment]
`ln -sf .env.development .env` seems far easier to me.

**Comment by mcollina** [comment]
I agree with James.

**Comment by Eomm** [comment]
You can still use it using the `data` option:

```
require('dotenv-flow').config();

const config = envSchema({
  schema: S.object().prop('port', S.string().default('3000').required()),
  data: process.env
})
```
