### ISSUE TITLE
A demo application with env-schema for reference - should we mention anywhere here to help others?

### ISSUE THREAD

**Issue by lirantal** [fastify/env-schema#142]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hey folks,

`env-schema` is great. I'm building a repository that demonstrates a fully functional Fastify application with `env-schema`, `fastify/env`, and `dotenv`. Would it be relevant to link it here anywhere in this or other repositories?

**Comment by mcollina** [comment]
Sure thing, I think it would be very useful!

**Comment by lirantal** [comment]
I'll workout a PR with updates for it.
