### ISSUE TITLE
config.data in the README file has to be config.ALLOWED_HOSTS?

### ISSUE THREAD

**Issue by aderchox** [fastify/env-schema#146]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

In the README file, below an example you have this comment:
```
// config.data => ['127.0.0.1', '0.0.0.0']
```
but it seems that it has to be this:
```
// config.ALLOWED_HOSTS => ['127.0.0.1', '0.0.0.0']
```
I tried on Runkit too, `config.data` logs `undefined`. Or I might be missing something...

**Comment by Eomm** [comment]
Thanks for reporting and yes you are right!
Would you like to send a Pull Request to address this issue?
