### ISSUE TITLE
Add the support to add formats

### ISSUE THREAD

**Issue by or2e** [fastify/env-schema#48]
## 🚀 Feature Proposal

Add the support to add formats `ajv-formats`

## Motivation

In https://github.com/ajv-validator/ajv/releases/tag/v7.0.0 formats was separated to https://github.com/ajv-validator/ajv-formats

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Giogia** [comment]
Has there been any recent development on adding support to custom `ajv` instances as suggested [here](https://github.com/fastify/env-schema/pull/52#issuecomment-810324587)?

**Comment by Fdawgs** [comment]
Closed by #76
