### ISSUE TITLE
feature: allow custom ajv instance

### ISSUE THREAD

**Issue by climba03003** [fastify/env-schema#72]
Instead of adding the support one by one. I suggest to allow user pass a custom `ajv` instance.

_Originally posted by @climba03003 in https://github.com/fastify/env-schema/issues/52#issuecomment-810324587_

Goal:
1. allow pass in custom `ajv` instance through option
2. expose the current keyword for the user to use
3. optional: add the current keyword to the custom `ajv` instance

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by stalniy** [comment]
After looking through the code, I decided that I need a completely different solution, so ended up with custom implementation of dotenv parser and `transform` ajv keyword - https://github.com/stalniy/jotenv

**Comment by Fdawgs** [comment]
Closed by #76
