### ISSUE TITLE
Use Ajv.errorsText instead of errors.map, otherwise you loose context

### ISSUE THREAD

**Issue by tommarien** [fastify/env-schema#78]
## 🚀 Feature Proposal

Suggestion to use the errorsText instead of the current custom formatter

## Motivation

Atm you loose context of which variable is wrong

```
Error: must be equal to one of the allowed values
```

## Example

If we would change the code to 

```js 
 if (!valid) {
    const error = new Error(ajv.errorsText(valid.errors, { dataVar: 'process.env'}))
    error.errors = ajv.errors
    throw error
  }
```

we would get following output

```
Error: process.env/LOG_LEVEL must be equal to one of the allowed values
```

I would not mind creating a pull request for it

**Comment by mcollina** [comment]
Go for it!
