### ISSUE TITLE
TS: Open up envSchemaData

### ISSUE THREAD

**Issue by tommarien** [fastify/env-schema#84]
## 🚀 Feature Proposal

Allow a type to be specified when using `envSchema()`.

## Motivation

This can be used to give a an interface or a typebox from json schema inferred interface

## Example

```ts
// change in type
declare const loadAndValidateEnvironment: {
  <T = EnvSchemaData>(_opts?: EnvSchemaOpt): T;
  keywords: {
    separator: KeywordDefinition;
  }
}
```

```ts
const schema = Schema.object()
  .prop('PORT', Schema.string());

interface Env {
  PORT?: string;
  LOG_LEVEL?: string;
  MONGO_URI: string;
  NODE_ENV?: string;
}

const env = envSchema<Env>({
  dotenv: !process.env.TAP,
  schema,
});

```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by tommarien** [comment]
@mcollina off course its about sharing or giving back to the fasting community 🤗
